#!/bin/bash

npm run make

rm -rf build
cp -a src/. build

# Удаляем артефакты
find build -name "*.md" -delete
find src/{t,invest} -name "*index.html" -delete

cd build

# Создаем Sitemap
SITEMAP=sitemap.txt
touch $SITEMAP
echo "https://voischev.ru/" > $SITEMAP
find ./{t,invest} -type d | sed "s/^\./https:\/\/voischev.ru/" | sed "s/$/\//" >> $SITEMAP
find ./{t,invest} -name "*.pdf" | sed "s/^./https:\/\/voischev.ru/" >> $SITEMAP

cd ..

tar -czf /tmp/voischev.ru.tar.gz build/
rm -rf build

scp /tmp/voischev.ru.tar.gz voischev@voischev:/tmp/

ssh voischev bash -s < scripts/server_publish

echo "Успешно"
